#!/usr/bin/env python

Import("env")
Import("env_modules")

env_minimp3 = env_modules.Clone()

# Godot's own source files
env_minimp3.add_source_files(env.modules_sources, "*.cpp")

if env_minimp3["platform"] == "linuxbsd":
    env_minimp3.Append(CPPFLAGS=["-Wno-shadow=compatible-local", "-Wno-error=shadow=local"])
