#!/usr/bin/env python

Import('env')
Import('env_modules')

env_minimp3 = env_modules.Clone()
#env_minimp3.Append(CPPPATH=["#thirdparty/minimp3"])

# Thirdparty source files
thirdparty_sources = []#["#thirdparty/minimp3/minimp3.h"]

env_thirdparty = env_minimp3.Clone()
env_thirdparty.disable_warnings()
env_thirdparty.add_source_files(env.modules_sources, thirdparty_sources)


# Godot's own source files
env_minimp3.add_source_files(env.modules_sources, "*.cpp")

#env_minimp3.Append(CCFLAGS=['-O2']) # Flags for C and C++ code
env_minimp3.Append(CXXFLAGS=['-std=c++11']) # Flags for C++ code only
